apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../ingress-nginx
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: sre-team
configMapGenerator:
  - name: ingress-nginx-internal-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
    options:
      disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
transformers:
  - transformer.yaml
patches:
- patch: |-
    - op: add
      path: /spec/valuesFrom/-
      value:
        kind: ConfigMap
        name: ingress-nginx-internal-values
        valuesKey: values.yaml
  target:
    group: helm.toolkit.fluxcd.io
    kind: HelmRelease
    name: ingress-nginx
    version: v2beta2
