apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/tenant: sre-team
configMapGenerator:
  - name: ingress-nginx-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml
    options:
      disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
