---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 20m
  timeout: 10m
  releaseName: ingress-nginx
  serviceAccountName: helm-controller
  targetNamespace: platform-ingress-nginx
  storageNamespace: platform-ingress-nginx
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: false
  chart:
    spec:
      chart: ingress-nginx
      version: "4.10.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 1m
  dependsOn:
    - name: cilium
      namespace: flux-system
    - name: aws-load-balancer-controller
      namespace: flux-system
    - name: kube-prometheus-stack
      namespace: flux-system
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-values
    valuesKey: values.yaml
