controller:
  networkPolicy:
    enabled: true
  allowSnippetAnnotations: true
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: DoNotSchedule
  - maxSkew: 1
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: DoNotSchedule
  replicaCount: 3
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: platform-ingress-nginx
      additionalLabels:
        release: kube-prometheus-stack
  podAnnotations:
    prometheus.io.scrape: 'true'
    prometheus.io.port: '10254'
  service:
    annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '10254'
  resources:
    limits:
      memory: 360Mi
    requests:
      cpu: 100m
      memory: 360Mi
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 50
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 98
